### ISSUE TITLE
檔案目錄結構調整

### ISSUE THREAD

**Issue by Julian-Chu** [andrew0928/Andrew.DiscountDemo#2]
目前csproj跟sln都在同一個根目錄下，後面增加專案會出error，
是否可以請安德魯大調整一下目錄結構 把專案移到子目錄。

**Comment by andrew0928** [comment]
抱歉時間有點晚了，現在改 structure 大家應該來不及重發 PR ..

沒關係，這次沒有要統一跑 benchmark, 重點都會擺在探討 code 的寫法, 真的有需要調整結構的話你可以直接改。

最後 PR 我會保留各位的 code 都有獨立的 branch, 真要 merge 我自己辛苦一次就好

**Comment by Julian-Chu** [comment]
謝謝 安德魯大 辛苦了
